version: '3'

services:
  app:
    container_name: app  
    restart: on-failure
    build: ./app
    volumes:
      - web-static:/static
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: on-failure
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - web-static:/static
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    container_name: db
    restart: on-failure
    build: ./db
    env_file:
      - ./app/config/.env

volumes: 
    web-static:
    pgdata: